[package]
name = "titanic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaggle-rs = { path = "../.." }
rusty-machine = "0.5.4"